---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jaeger-gw
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "jaeger.istio.toddelewis.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-vs
  namespace: istio-system
spec:
  hosts:
  - "jaeger.istio.toddelewis.net"
  gateways:
  - jaeger-gw
  http:
  - route:
    - destination:
        port:
          number: 16686
        host: jaeger-query

