---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kibana-gw
  namespace: logging
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "kibana.istio.toddelewis.net"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana-vs
  namespace: logging
spec:
  hosts:
  - "kibana.istio.toddelewis.net"
  gateways:
  - kibana-gw
  http:
  - route:
    - destination:
        port:
          number: 5601
        host: kibana
